WMO_CODES = {
    0:  ("Clear",        "Clear sky"),
    1:  ("Clear",        "Mainly clear"),
    2:  ("Cloudy",       "Partly cloudy"),
    3:  ("Cloudy",       "Overcast"),
    45: ("Fog",          "Fog"),
    48: ("Fog",          "Depositing rime fog"),
    51: ("Drizzle",      "Light drizzle"),
    53: ("Drizzle",      "Moderate drizzle"),
    55: ("Drizzle",      "Dense drizzle"),
    56: ("Drizzle",      "Light freezing drizzle"),
    57: ("Drizzle",      "Heavy freezing drizzle"),
    61: ("Rain",         "Slight rain"),
    63: ("Rain",         "Moderate rain"),
    65: ("Rain",         "Heavy rain"),
    66: ("Rain",         "Light freezing rain"),
    67: ("Rain",         "Heavy freezing rain"),
    71: ("Snow",         "Slight snowfall"),
    73: ("Snow",         "Moderate snowfall"),
    75: ("Snow",         "Heavy snowfall"),
    77: ("Snow",         "Snow grains"),
    80: ("Rain",         "Slight rain showers"),
    81: ("Rain",         "Moderate rain showers"),
    82: ("Rain",         "Violent rain showers"),
    85: ("Snow",         "Slight snow showers"),
    86: ("Snow",         "Heavy snow showers"),
    95: ("Thunderstorm", "Thunderstorm"),
    96: ("Thunderstorm", "Thunderstorm with slight hail"),
    99: ("Thunderstorm", "Thunderstorm with heavy hail"),
}